name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "develop" ] # This line ensures builds trigger for both branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKOCKERHUB_USERNAME }} # Double-check secret name
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Double-check secret name

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # This builds and tags the image as 'latest' regardless of the branch
          tags: syprix/unraid-internxt-cli:latest
